"""updated models to include index

Revision ID: a7e810f183f7
Revises: d8b3457a0ccb
Create Date: 2026-06-22 22:09:30.755290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e810f183f7'
down_revision: Union[str, Sequence[str], None] = 'd8b3457a0ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.add_column('users', sa.Column('hashed_refresh_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_refresh_token')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    # ### end Alembic commands ###
