"""Add taskRequestRecord table

Revision ID: c2bd58c1aa45
Revises: a7e810f183f7
Create Date: 2026-06-29 21:35:06.228022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bd58c1aa45'
down_revision: Union[str, Sequence[str], None] = 'a7e810f183f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_request_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('request_by', sa.UUID(), nullable=False),
    sa.Column('request_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'request_by', name='uc_task_request')
    )
    op.create_index(op.f('ix_task_request_records_request_by'), 'task_request_records', ['request_by'], unique=False)
    op.create_index(op.f('ix_task_request_records_task_id'), 'task_request_records', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_request_records_task_id'), table_name='task_request_records')
    op.drop_index(op.f('ix_task_request_records_request_by'), table_name='task_request_records')
    op.drop_table('task_request_records')
    # ### end Alembic commands ###
